# Generated by Django 5.2.4 on 2025-07-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oredr',
            new_name='order',
        ),
    ]
